language: csharp
solution: GDOTtrafficsystem.sln
branches:
  only:
    - master
notifications:
  email: false
  hipchat: 587277e57c288cf83baf3695be8193@1315892
script:
  - chmod +x ./build.sh
  - ./build.sh
deploy:
  provider: releases
  api_key: "decd3221b01481876b77d479bddbacadb694aa8c"
  file:
    - "./latest.tar.gz"
  skip_cleanup: true
  on:
    tags: true
